#%RAML 1.0 NamedExample
value: |
    {
    "amount": 1050,
    "currency": "USD",
    "payment_method": {
        "cardtype": "us_visa_card",
        "fields": {
            "cardnumber": "4111111111111111",
            "expiration_month": "12",
            "expiration_year": "25",
            "cvv": "789",
            "name": "John Doe"
        }
    }
    }