#%RAML 1.0 NamedExample
value: |
        [                  
          {
            "customerId": "provider_0123456789",
            "items": [
                {
                  "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
                  "quantity": 1
                },
                {
                  "productId": "cd67cd8a-8901-48c5-890b-0a21f4a0f8ad",
                  "quantity": 1

                }
              ]
           }
         ]